---
- hosts: localhost
  tasks:
  - name: "shut down CentOS 6 systems"
    touch: /opt/verizon.txt
    when:
      - ansible_distribution == "RedHat"
      - ansible_distribution_major_version == "7.5"
